# Generated by Django 5.0.6 on 2025-02-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
