# Generated by Django 5.0.6 on 2025-03-06 09:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="Category that matches the Post content.",
                on_delete=models.SET(core.models.get_or_create_uncategorized),
                to="core.category",
            ),
            preserve_default=False,
        ),
    ]
