# Generated by Django 5.0.6 on 2025-03-13 08:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
