# Generated by Django 5.0.6 on 2025-03-13 09:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_category_unique_color_category_unique_color"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_color",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("color"),
                name="unique_lower_color",
                violation_error_message="This color already exists (Capital- and Lowercase is ignored).",
            ),
        ),
    ]
