# Generated by Django 5.0.6 on 2025-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_categories_through_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="posts", through="core.PostCategory", to="core.category"
            ),
        ),
    ]
