# Generated by Django 5.2 on 2025-06-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image that represents the post.",
                null=True,
                upload_to="posts/images/",
            ),
        ),
    ]
