# Generated by Django 5.2 on 2025-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image that represents the post.",
                null=True,
                upload_to="C:\\dev\\Tests\\django-example\\medias/posts",
            ),
        ),
    ]
