# Generated by Django 5.2 on 2025-07-31 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subordinates",
                to="core.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent_category", models.F("id")), _negated=True),
                name="prevent_self_reference",
                violation_error_message="Category cannot reference itself!",
            ),
        ),
    ]
