# Generated by Django 5.2 on 2025-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_category_parent_category_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="name_populated"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("color", ""), _negated=True), name="color_populated"
            ),
        ),
    ]
