# Generated by Django 5.0.6 on 2025-02-27 09:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_alter_post_author_alter_post_description_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_lower_name",
                violation_error_message="This Name already exists (Capital- and Lowercase is ignored).",
            ),
        ),
    ]
