# Generated by Django 5.0.6 on 2025-02-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category_unique_lower_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": ("Categories",)},
        ),
    ]
