# Generated by Django 5.0.6 on 2025-03-06 08:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                choices=[("#FFFFFF", "white"), ("#000000", "black")],
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
    ]
