# Generated by Django 5.0.6 on 2025-03-13 09:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_category_color_alter_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_color",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("color"),
                name="unique_color",
                violation_error_message="This color already exists.",
            ),
        ),
    ]
