# Generated by Django 5.0.6 on 2025-03-27 12:04

import datetime
from django.db import migrations
from django.apps.registry import Apps


def create_through_relations(apps: Apps, schema_editor):
    Post = apps.get_model("core", "Post")
    PostCategory = apps.get_model("core", "PostCategory")
    for post in Post.objects.all():
        for category in post.categories.all():
            PostCategory(post=post, category=category, date_created=datetime.date.today()).save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_post_categories_through"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
