# Generated by Django 5.0.6 on 2025-03-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20250327_1304"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
    ]
