# Generated by Django 5.2 on 2026-03-09 17:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_category_name_populated_category_color_populated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image that represents the post.",
                null=True,
                upload_to=core.models.post_directory_path,
            ),
        ),
        migrations.AlterConstraint(
            model_name="category",
            name="name_populated",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="name_populated",
                violation_error_message="Name can not be empty!",
            ),
        ),
        migrations.AlterConstraint(
            model_name="category",
            name="color_populated",
            constraint=models.CheckConstraint(
                condition=models.Q(("color", ""), _negated=True),
                name="color_populated",
                violation_error_message="Color can not be empty!",
            ),
        ),
    ]
