name: Linting

on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Requirements
        run: pip install -r requirements-dev.txt
      - name: Run Linting
        run: flake8 --config=flake8.ini ./
      
  
