name: Prevent Staging Merge

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '**' # Run the check on all branches when pushed

jobs:
  prevent-staging-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Allow pushes and PRs to staging
        run: |
          # Skip the check if the target branch is staging
          if [ "${{ github.ref_name }}" = "staging" ]; then
              echo "✅ Push or pull request to 'staging' is allowed."
              exit 0
          fi

      - name: Verify staging is not merged
        run: |
          if git merge-base --is-ancestor origin/staging HEAD; then
              echo "❌ Error: Commits from 'staging' cannot be merged into other branches."
              exit 1
          fi
